# -*- coding: utf-8 -*-
"""bruteforce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPkvssqsTBC-akZGSBPb9B_LE_EFOPUb
"""

import time
alphabet = "abcdefghijklmnopqrstuvwxyz"
alphabetM = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
simbolo = "!@#(){}[]*=+´'-_.,;><"
numeros = "1234567890"

todos = alphabet + alphabetM + simbolo + numeros

contraseña = "hol#>!*JL"
resultado = ""
intentos = 0
inicial = time.time()

for letra in contraseña:
    for intento in todos:

        intentos += 1
        if intento == letra:
            resultado += intento
            break
        else:
            print("intento fallido")

final = time.time()

if contraseña == resultado:
  print("Encontrado:", resultado)

print("Total de intentos:", intentos)
print("Total de tiempo:", time.time() - inicial)